name: useitall
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_emoji: ^2.0.0
  csv: ^5.0.0
  intl: ^0.17.0  # Add this line


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/recipes.csv
    - assets/ingredient_category_macros.csv